@echo off
echo Cleaning Flutter build cache...
cd /d "%~dp0customer_app"

echo Step 1: Stopping any running Flutter processes...
taskkill /F /IM dart.exe 2>nul
timeout /t 2 /nobreak >nul

echo Step 2: Cleaning build files...
call flutter clean

echo Step 3: Getting dependencies...
call flutter pub get

echo Step 4: Launching with CORS disabled...
flutter run -d chrome --web-browser-flag="--disable-web-security" --web-browser-flag="--user-data-dir=%TEMP%\chrome-dev-indulink"
